package itt.lnc.news_aggregation_client.constants;

public enum MenuType {
    MAIN,
    ADMIN,
    USER,
    EXTERNAL_SERVER,
    MANAGE_CATEGORIES,
    MANAGE_KEYWORDS,
    MANAGE_REPORTED_ARTICLES,
    HEADLINES, CATEGORIES, ARTICLE_LIST, SAVED_ARTICLES, SEARCH, NOTIFICATIONS,
}
