spring.datasource.url=jdbc:mysql://localhost:3306/news_aggregation
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

security.jwt.secret-key=13b489021a69308fb52ae01fc68de739a5cdecceeb175388aa52f4060227c651
security.jwt.expiration-time=3600000

article.report.threshold=1

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aryan.nama001@gmail.com
spring.mail.password=djlpdmtqmlqolexk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true